FROM node:21-alpine3.18

# Create app directory
WORKDIR /app

# Install app dependencies
COPY package.json /app
RUN yarn install

COPY tsconfig.json /app
COPY api /app/api
COPY prisma /app/prisma
COPY src /app/src
COPY CustomerService /app/CustomerService

RUN yarn run build:customerservice

EXPOSE 3000

CMD ["node", "-r", "tsconfig-paths/register", "CustomerService/dist/CustomerService/src/server.js"]
