FROM node:21-alpine3.18

# Create app directory
WORKDIR /app

# Install app dependencies
COPY package.json /app
RUN yarn install

COPY tsconfig.json /app
COPY api /app/api
COPY prisma /app/prisma
COPY src /app/src
COPY MobileBFF /app/MobileBFF

RUN yarn run build:mobilebff

EXPOSE 80

CMD ["node", "-r", "tsconfig-paths/register", "MobileBFF/dist/MobileBFF/src/server.js"]
