FROM node:21-alpine3.18

# Create app directory
WORKDIR /app

# Install app dependencies
COPY package.json /app
RUN yarn install

COPY tsconfig.json /app
COPY api /app/api
COPY prisma /app/prisma
COPY src /app/src
COPY EmailService /app/EmailService

RUN yarn run build:emailservice

EXPOSE 3000

CMD ["node", "-r", "tsconfig-paths/register", "EmailService/dist/EmailService/src/server.js"]
