apiVersion: v1
kind: Service
metadata:
  name: crmservice-clusterip-service
  namespace: bookstore-ns
spec:
  type: LoadBalancer
  selector:
    app: crmservice
  ports:
  - port: 3000
    targetPort: 3000
