apiVersion: v1
kind: Service
metadata:
  name: customerservice-clusterip-service
  namespace: bookstore-ns
spec:
  type: LoadBalancer
  selector:
    app: customerservice
  ports:
  - port: 3000
    targetPort: 3000
