apiVersion: v1
kind: Service
metadata:
  name: mobilebbf-clusterip-service
  namespace: bookstore-ns
spec:
  type: LoadBalancer
  selector:
    app: mobilebbf
  ports:
  - port: 80
    targetPort: 80
